"""initial schema

Revision ID: 95b53bb54416
Revises: 
Create Date: 2026-09-19 02:04:58.448250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95b53bb54416'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level > 0', name='ck_ranks_level_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', name='uq_ranks_level'),
    sa.UniqueConstraint('name', name='uq_ranks_name')
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('training_type', sa.Text(), nullable=False),
    sa.Column('instructor_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('capacity', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("training_type IN ('firearms', 'legal', 'physical', 'cyber', 'first_aid', 'ethics')", name='ck_training_sessions_type'),
    sa.CheckConstraint('capacity > 0', name='ck_training_sessions_capacity'),
    sa.CheckConstraint('end_date >= start_date', name='ck_training_sessions_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_sessions_start_date', 'training_sessions', ['start_date'], unique=False)
    op.execute(
        "CREATE TRIGGER trg_training_sessions_updated_at "
        "BEFORE UPDATE ON training_sessions "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit_type', sa.Enum('headquarters', 'division', 'precinct', 'special_unit', name='unit_type_enum'), nullable=False),
    sa.Column('parent_unit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_unit_id IS DISTINCT FROM id', name='ck_units_not_own_parent'),
    sa.ForeignKeyConstraint(['parent_unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_units_name')
    )
    op.execute(
        "CREATE TRIGGER trg_units_updated_at "
        "BEFORE UPDATE ON units "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badge_number', sa.String(length=15), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('rank_id', sa.Integer(), nullable=False),
    sa.Column('current_unit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'on_leave', 'suspended', 'retired', 'terminated', name='officer_status_enum'), server_default='active', nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', postgresql.CITEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("badge_number ~ '^[A-Z]{2,4}-[0-9]{4,6}$'", name='ck_officers_badge_format'),
    sa.CheckConstraint("date_joined >= date_of_birth + INTERVAL '18 years'", name='ck_officers_min_age'),
    sa.CheckConstraint('date_joined > date_of_birth', name='ck_officers_joined_after_birth'),
    sa.ForeignKeyConstraint(['current_unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_number', name='uq_officers_badge_number'),
    sa.UniqueConstraint('contact_email', name='uq_officers_contact_email')
    )
    op.create_index('idx_officers_active_unit', 'officers', ['current_unit_id'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_officers_current_unit_id', 'officers', ['current_unit_id'], unique=False)
    op.create_index('idx_officers_rank_id', 'officers', ['rank_id'], unique=False)
    op.execute(
        "CREATE TRIGGER trg_officers_updated_at "
        "BEFORE UPDATE ON officers "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('operation_type', sa.Enum('raid', 'patrol_sweep', 'checkpoint', 'investigation', 'surveillance', 'crowd_control', name='operation_type_enum'), nullable=False),
    sa.Column('status', sa.Text(), server_default='planned', nullable=False),
    sa.Column('lead_unit_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'active', 'completed', 'cancelled')", name='ck_operations_status'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_operations_dates'),
    sa.ForeignKeyConstraint(['lead_unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operations_active', 'operations', ['status'], unique=False, postgresql_where=sa.text("status IN ('planned', 'active')"))
    op.create_index('idx_operations_lead_unit_id', 'operations', ['lead_unit_id'], unique=False)
    op.execute(
        "CREATE TRIGGER trg_operations_updated_at "
        "BEFORE UPDATE ON operations "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_number', sa.String(length=20), nullable=False),
    sa.Column('incident_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incident_severity_enum'), server_default='low', nullable=False),
    sa.Column('status', sa.Text(), server_default='reported', nullable=False),
    sa.Column('reported_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('location_description', sa.String(length=200), nullable=False),
    sa.Column('reporting_officer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_unit_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("incident_type IN ('theft', 'assault', 'traffic', 'homicide', 'fraud', 'public_disturbance', 'other')", name='ck_incidents_type'),
    sa.CheckConstraint("status IN ('reported', 'under_investigation', 'resolved', 'closed')", name='ck_incidents_status'),
    sa.ForeignKeyConstraint(['assigned_unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporting_officer_id'], ['officers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_number', name='uq_incidents_incident_number')
    )
    op.create_index('idx_incidents_assigned_unit_id', 'incidents', ['assigned_unit_id'], unique=False)
    op.create_index('idx_incidents_open', 'incidents', ['status'], unique=False, postgresql_where=sa.text("status IN ('reported', 'under_investigation')"))
    op.create_index('idx_incidents_operation_id', 'incidents', ['operation_id'], unique=False)
    op.create_index('idx_incidents_reporting_officer_id', 'incidents', ['reporting_officer_id'], unique=False)
    op.execute(
        "CREATE TRIGGER trg_incidents_updated_at "
        "BEFORE UPDATE ON incidents "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )
    op.create_table('operation_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('role_in_operation', sa.Text(), server_default='participant', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role_in_operation IN ('lead', 'participant', 'support')", name='ck_operation_participants_role'),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', 'officer_id', name='uq_operation_participants')
    )
    op.create_index('idx_operation_participants_officer_id', 'operation_participants', ['officer_id'], unique=False)
    op.create_table('patrols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('patrol_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('morning', 'evening', 'night', name='shift_enum'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('vehicle_code', sa.String(length=20), nullable=True),
    sa.Column('area_description', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Text(), server_default='scheduled', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'in_progress', 'completed', 'cancelled')", name='ck_patrols_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_patrols_times'),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patrols_officer_id', 'patrols', ['officer_id'], unique=False)
    op.create_index('idx_patrols_patrol_date', 'patrols', ['patrol_date'], unique=False)
    op.create_index('idx_patrols_unit_id', 'patrols', ['unit_id'], unique=False)
    op.execute(
        "CREATE TRIGGER trg_patrols_updated_at "
        "BEFORE UPDATE ON patrols "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('from_rank_id', sa.Integer(), nullable=True),
    sa.Column('to_rank_id', sa.Integer(), nullable=False),
    sa.Column('promotion_date', sa.Date(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_rank_id IS DISTINCT FROM to_rank_id', name='ck_promotions_rank_change'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['officers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_rank_id'], ['ranks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_rank_id'], ['ranks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_promotions_officer_id', 'promotions', ['officer_id'], unique=False)
    op.create_index('idx_promotions_promotion_date', 'promotions', ['promotion_date'], unique=False)
    op.create_table('training_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('attendance_status', sa.Text(), server_default='registered', nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('certificate_issued', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("attendance_status IN ('registered', 'attended', 'absent', 'excused')", name='ck_training_attendance_status'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_training_attendance_score'),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id', 'officer_id', name='uq_training_attendance')
    )
    op.create_index('idx_training_attendance_officer_id', 'training_attendance', ['officer_id'], unique=False)
    op.create_table('unit_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.Enum('permanent', 'temporary', 'detached', name='assignment_type_enum'), server_default='permanent', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_unit_assignments_dates'),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unit_assignments_officer_id', 'unit_assignments', ['officer_id'], unique=False)
    op.create_index('idx_unit_assignments_unit_id', 'unit_assignments', ['unit_id'], unique=False)
    op.create_index('uq_unit_assignments_open_officer', 'unit_assignments', ['officer_id'], unique=True, postgresql_where=sa.text('end_date IS NULL'))
    op.execute(
        "CREATE TRIGGER trg_unit_assignments_updated_at "
        "BEFORE UPDATE ON unit_assignments "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'supervisor', 'officer', 'viewer', name='user_role_enum'), server_default='officer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index('uq_users_officer_id', 'users', ['officer_id'], unique=True, postgresql_where=sa.text('officer_id IS NOT NULL'))
    op.execute(
        "CREATE TRIGGER trg_users_updated_at "
        "BEFORE UPDATE ON users "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('INSERT', 'UPDATE', 'DELETE')", name='ck_audit_logs_action'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_table_record', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_officer_id', table_name='users', postgresql_where=sa.text('officer_id IS NOT NULL'))
    op.drop_table('users')
    op.drop_index('uq_unit_assignments_open_officer', table_name='unit_assignments', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_index('idx_unit_assignments_unit_id', table_name='unit_assignments')
    op.drop_index('idx_unit_assignments_officer_id', table_name='unit_assignments')
    op.drop_table('unit_assignments')
    op.drop_index('idx_training_attendance_officer_id', table_name='training_attendance')
    op.drop_table('training_attendance')
    op.drop_index('idx_promotions_promotion_date', table_name='promotions')
    op.drop_index('idx_promotions_officer_id', table_name='promotions')
    op.drop_table('promotions')
    op.drop_index('idx_patrols_unit_id', table_name='patrols')
    op.drop_index('idx_patrols_patrol_date', table_name='patrols')
    op.drop_index('idx_patrols_officer_id', table_name='patrols')
    op.drop_table('patrols')
    op.drop_index('idx_operation_participants_officer_id', table_name='operation_participants')
    op.drop_table('operation_participants')
    op.drop_index('idx_incidents_reporting_officer_id', table_name='incidents')
    op.drop_index('idx_incidents_operation_id', table_name='incidents')
    op.drop_index('idx_incidents_open', table_name='incidents', postgresql_where=sa.text("status IN ('reported', 'under_investigation')"))
    op.drop_index('idx_incidents_assigned_unit_id', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('idx_operations_lead_unit_id', table_name='operations')
    op.drop_index('idx_operations_active', table_name='operations', postgresql_where=sa.text("status IN ('planned', 'active')"))
    op.drop_table('operations')
    op.drop_index('idx_officers_rank_id', table_name='officers')
    op.drop_index('idx_officers_current_unit_id', table_name='officers')
    op.drop_index('idx_officers_active_unit', table_name='officers', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('officers')
    op.drop_table('units')
    op.drop_index('idx_training_sessions_start_date', table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_table('ranks')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.execute("DROP EXTENSION IF EXISTS citext")
    for enum_name in (
        "gender_enum",
        "officer_status_enum",
        "user_role_enum",
        "unit_type_enum",
        "assignment_type_enum",
        "operation_type_enum",
        "incident_severity_enum",
        "shift_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
